server:
  port: 8081
spring:
  application:
    name: spotifyRunning
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: add_spotify_app_client_id
            client-secret: add_spotify_app_client_secret
            provider: spotify
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: user-read-email, user-top-read, playlist-modify-public, playlist-modify-private
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize?show_dialog=false
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: display_name

app:
  playlist:
    name: "Running workout"
    description: "Music for your training based on Spotify recommendations and specific audio features"
    features:
      min-tempo: "185"
      max-tempo: "205"
      min-energy: "0.65"
  requests:
    get-user-top-items:
      limit: 1
    get-recommendations:
      limit: 50
      time-range: medium_term
  limits:
    playlist-size: 50

logging:
  level:
    com.ksaraev.spotifyrunning.client.SpotifyClient: DEBUG
